services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: espaco_lounge
    ports:
      - '5432:5432'
    volumes:
      - espaco_pg:/var/lib/postgresql/data

volumes:
  espaco_pg:
